<!-- For admin kit Local scripts-->
<script src="<?php echo SITE_URL; ?>/vendor/js/jquery.min.js"></script>
<script src="<?php echo SITE_URL; ?>/vendor/js/popper.min.js"></script>
<script src="<?php echo SITE_URL; ?>/vendor/bootstrap4.3.1/js/bootstrap.min.js"></script>
<script src="<?php echo SITE_URL; ?>/vendor/bootstrap4.3.1/js/bootstrap.bundle.min.js"></script>
<!-- jQuery Custom Scroller CDN -->
<script src="<?php echo SITE_URL; ?>/vendor/js/jquery.mCustomScrollbar.concat.min.js"></script>

<!-- DataTable script -->
<script type="text/javascript" charset="utf8" src="<?php echo SITE_URL; ?>/vendor/DataTables/DataTables-1.10.20/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="<?php echo SITE_URL; ?>/vendor/DataTables/datatables.js"></script>

<!-- Custom scripts for kit admin part used also for general part-->
<script src="<?php echo SITE_URL_ADMIN; ?>/vendor/js/sb-admin-2.min.js"></script>

<!--Customized script for admin kit -->
<script src="<?php echo SITE_URL_ADMIN; ?>/js/script.js"></script>
