<!--Kit Admin-->
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="">
<meta name="author" content="Antonina NGUYEN">
<!--Customized style-->
<link rel="stylesheet" href="<?php echo SITE_URL_ADMIN; ?>/css/style.css">
<!--Local Bootstrap style-->
<link rel="stylesheet" href="<?php echo SITE_URL; ?>/vendor/bootstrap4.3.1/css/bootstrap.min.css">
<!-- Custom fonts for this template-->
<link href="<?php echo SITE_URL; ?>/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
<!-- Custom styles for kit-admin -->
 <link href="<?php echo SITE_URL_ADMIN;?>/vendor/css/sb-admin-2.min.css" rel="stylesheet">
<!--Cusomized style for alerts -->
<link charset="utf-8" rel="stylesheet" type="text/css" href="<?php echo SITE_URL;?>/vendor/css/smoke-pure.css" />
<script type="text/javascript" src="<?php echo SITE_URL_ADMIN;?>/vendor/js/smoke-pure.js"></script>

<!-- DataTables -->
<link rel="stylesheet" type="text/css" href="<?php echo SITE_URL; ?>/vendor/DataTables/datatables.css">

<title><?php echo $titlePage ?></title>
