<!-- For main pages Local scripts-->
<script src="<?php echo SITE_URL; ?>/vendor/js/jquery.min.js"></script>

<script src="<?php echo SITE_URL; ?>/vendor/bootstrap4.3.1/js/bootstrap.min.js"></script>

<script src="<?php echo SITE_URL; ?>/vendor/js/popper.min.js"></script>
<script src="<?php echo SITE_URL; ?>/vendor/bootstrap4.3.1/js/bootstrap.bundle.min.js"></script>
<script src="<?php echo SITE_URL; ?>/vendor/fontawesome-free/js/all.min.js"></script>
<!-- jQuery Custom Scroller CDN -->
<script src="<?php echo SITE_URL; ?>/vendor/js/jquery.mCustomScrollbar.concat.min.js"></script>

<!-- Custom scripts for kit admin part used also for general part
<script src="<?php echo SITE_URL_ADMIN; ?>/js/sb-admin-2.min.js"></script>-->
<script src="<?php echo SITE_URL; ?>/vendor/js/pushy.min.js"></script>
<!-- Script personalized -->

<!-- DataTable script -->
<script type="text/javascript" charset="utf8" src="<?php echo SITE_URL; ?>/vendor/DataTables/DataTables-1.10.20/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="<?php echo SITE_URL; ?>/vendor/DataTables/Responsive-2.2.3/js/dataTables.responsive.min.js"></script>
<script type="text/javascript" charset="utf8" src="<?php echo SITE_URL; ?>/vendor/DataTables/datatables.js"></script>
<script type="text/javascript" charset="utf8" src="<?php echo SITE_URL; ?>/vendor/DataTables/Buttons-1.6.1/js/dataTables.buttons.min.js"></script>  
<script type="text/javascript" charset="utf8" src="<?php echo SITE_URL; ?>/vendor/DataTables/pdfmake-0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" charset="utf8" src="<?php echo SITE_URL; ?>/vendor/DataTables/Buttons-1.6.1/js/buttons.html5.min.js"></script>
<script type="text/javascript" charset="utf8" src="<?php echo SITE_URL; ?>/vendor/DataTables/Buttons-1.6.1/js/buttons.print.min.js"></script>

<!-- Customised script for Main page -->
<script src="<?php echo SITE_URL; ?>/js/script.js"></script>


